### ISSUE TITLE
request for preprocessed data

### ISSUE THREAD

**Issue by doublejingz** [DineshRaghu/multi-level-memory-network#1]
Hello, 

Thanks for your code for "Multi-Level Memory for Task Oriented Dialogs".

I want to run the code, but I find that your data is not original data which has been preprocessed, would you mind provide the preprocessed data or basic data_loader.py for truly running?

**Comment by DineshRaghu** [comment]
@doublejingz Thank you for your interest! I will provide them in a day or two.

**Comment by doublejingz** [comment]
Thanks a lot and I am looking forward to it.

**Comment by doublejingz** [comment]
Thanks a lot and I am looking forward to it.

**Comment by DineshRaghu** [comment]
@doublejingz: The [PR](https://github.com/DineshRaghu/multi-level-memory-network/pull/2) from @revanth1996 contains the data requested.

I am closing this issue.
